### PR TITLE
Chris yazan2

### PR DESCRIPTION
**Pull request by chrisy1225**
We deleted unnecessary components from the template and implemented the chat thread.

### CODE REVIEW

**Comment by Succion** [comment]
Seems like there is a bit of conflict at routes.js. Can you fix it really fast?

**Comment by chrisy1225** [comment]
> Seems like there is a bit of conflict at routes.js. Can you fix it really fast?

Those are just deleting the unnecessary components that were there by default in the template. I don't think it should matter that much?

**Review by Succion — APPROVED** [review]
Aighty good work!

**Review by Succion — CHANGES_REQUESTED** [review]
The auto ran checks did not pass. Maybe something to do with TableList

**Review by Succion — APPROVED** [review]

**Review by Succion — APPROVED** [review]

**Pull request merged**
